# Generated by Django 5.2.14 on 2026-05-07 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='场馆名称')),
                ('address', models.CharField(max_length=255, verbose_name='场馆地址')),
                ('phone_number', models.CharField(max_length=20, verbose_name='联系电话')),
                ('information', models.TextField(blank=True, verbose_name='场馆简介')),
                ('audit_status', models.CharField(choices=[('pending', '待审核'), ('approved', '通过'), ('rejected', '不通过')], default='pending', max_length=20, verbose_name='审核状态')),
                ('is_open', models.BooleanField(default=False, verbose_name='开放状态')),
                ('deletion_requested', models.BooleanField(default=False, verbose_name='申请删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stadiums', to=settings.AUTH_USER_MODEL, verbose_name='场馆管理员')),
            ],
            options={
                'verbose_name': '体育场馆',
                'verbose_name_plural': '体育场馆',
                'ordering': ['-updated_at'],
            },
        ),
    ]
