# Generated by Django 5.2.14 on 2026-05-07 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(max_length=50, verbose_name='场地类型')),
                ('number', models.CharField(max_length=50, verbose_name='场地编号')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='预约单价/小时')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='stadiums.stadium', verbose_name='场馆')),
            ],
            options={
                'verbose_name': '场地',
                'verbose_name_plural': '场地',
                'ordering': ['stadium', 'number'],
                'unique_together': {('stadium', 'number')},
            },
        ),
    ]
