# Generated by Django 5.2.14 on 2026-05-07 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0002_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='开放日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('is_available', models.BooleanField(default=True, verbose_name='可约状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='stadiums.field', verbose_name='场地')),
            ],
            options={
                'verbose_name': '开放时段',
                'verbose_name_plural': '开放时段',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
