# Generated by Django 5.2.14 on 2026-05-24 07:21

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone
from uuid import uuid4


def create_payments_for_existing_reservations(apps, schema_editor):
    Reservation = apps.get_model('reservations', 'Reservation')
    Payment = apps.get_model('reservations', 'Payment')
    for reservation in Reservation.objects.select_related('time_slot__field'):
        if Payment.objects.filter(reservation_id=reservation.pk).exists():
            continue
        payment_status = 'paid' if reservation.status in {'pending', 'approved'} else 'closed'
        payment = Payment.objects.create(
            reservation_id=reservation.pk,
            payment_no=uuid4().hex,
            amount=reservation.time_slot.field.price_per_hour,
            status=payment_status,
        )
        if payment_status == 'paid':
            Payment.objects.filter(pk=payment.pk).update(paid_at=timezone.now())
        elif payment_status == 'closed':
            Payment.objects.filter(pk=payment.pk).update(closed_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', '待支付'), ('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已取消'), ('payment_failed', '支付失败')], default='awaiting_payment', max_length=20, verbose_name='预约状态'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(blank=True, max_length=40, unique=True, verbose_name='支付流水号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='支付金额')),
                ('status', models.CharField(choices=[('unpaid', '待支付'), ('paid', '已支付'), ('failed', '支付失败'), ('closed', '已关闭'), ('refunded', '已退款')], default='unpaid', max_length=20, verbose_name='支付状态')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='reservations.reservation', verbose_name='预约')),
            ],
            options={
                'verbose_name': '支付单',
                'verbose_name_plural': '支付单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(create_payments_for_existing_reservations, migrations.RunPython.noop),
    ]
